[env:esp32-s3-relay]
platform = espressif32
board = esp32s3box
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -D SWIFT_CABIN_CONTROLLER
lib_deps =
  arduino-libraries/DHT sensor library @ ^1.4.4
  paulstoffregen/Time @ ^1.6
